name: flutter_debounce_throttle_hooks
description: >-
  Flutter Hooks integration for flutter_debounce_throttle.
  Auto-dispose debounce and throttle controllers with HookWidget.
version: 2.4.2
homepage: https://github.com/brewkits/flutter_debounce_throttle
repository: https://github.com/brewkits/flutter_debounce_throttle
issue_tracker: https://github.com/brewkits/flutter_debounce_throttle/issues

topics:
  - debounce
  - throttle
  - flutter-hooks
  - async
  - ui

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3
  flutter_debounce_throttle: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

flutter:
