name: flutter_debounce_throttle
description: Safe event limiting for Flutter with auto lifecycle management. Debounce, throttle, prevent double-clicks and race conditions.
version: 1.0.1
homepage: https://github.com/brewkits/flutter_debounce_throttle
repository: https://github.com/brewkits/flutter_debounce_throttle
issue_tracker: https://github.com/brewkits/flutter_debounce_throttle/issues

topics:
  - debounce
  - throttle
  - rate-limiting
  - async
  - ui

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_debounce_throttle_core: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

flutter:
