name: flutter_debounce_throttle_core
description: Pure Dart debounce, throttle, and rate limiting. Zero dependencies, works everywhere - Mobile, Web, Desktop, Server, CLI.
version: 1.1.1
homepage: https://github.com/brewkits/flutter_debounce_throttle
repository: https://github.com/brewkits/flutter_debounce_throttle
issue_tracker: https://github.com/brewkits/flutter_debounce_throttle/issues

topics:
  - debounce
  - throttle
  - rate-limiting
  - async
  - dart

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.16.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.29.0
